export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',

    APP: '/app',
    DASHBOARD: '/app/dashboard',
    QUESTIONS: '/app/questions',
    QUESTIONS_ADD: '/app/questions/add',
    EXAMS: '/app/exams',
    EXAMS_CREATE: '/app/exams/create',
    EXAM_LIST: '/app/exam-list',
    EXAM_DETAIL: '/app/exam-list/:id',
    SUBMISSION_REVIEW: '/app/submissions/:id/review',
    EXAM_SESSIONS: '/app/exam-sessions',
    EXAM_SESSIONS_CREATE: '/app/exam-sessions/create',
    CATEGORY: '/app/category',
    GENERATE: '/app/generate',
    USERS: '/app/users',
    SCHOOLS: '/app/schools',
    PROFILE: '/app/profile',
    FORBIDDEN: '/forbidden',
    NO_ROLE: '/no-role',

    STUDENT_EXAMS: '/student/exams',
    STUDENT_SESSION_POOL: '/student/session/:id/pool',
    STUDENT_PROFILE: '/student/profile',
    STUDENT_EXAM: '/student/exam',
    STUDENT_EXAM_TAKE: '/student/exam/take',
} as const
