services:
#  api:
#    build:
#      context: ./ExamHub.API
#      dockerfile: Dockerfile
#    container_name: api
#    restart: unless-stopped
#    ports:
#      - "5000:8080"
#    environment:
#      ConnectionStrings__Default: ""
#      ConnectionStrings__MongoDB: ""
#      Redis__ConnectionString: ""
#      MinIO__Endpoint: "minio:9000"
#      MinIO__AccessKey: ""
#      MinIO__SecretKey: ""
#      RabbitMQ__Host: "rabbitmq"
#      RabbitMQ__Username: ""
#      RabbitMQ__Password: ""
#      Jwt__SecretKey: ""
#      Jwt__Issuer: "ExamHub"
#      Jwt__Audience: "ExamHubUsers"
#    depends_on:
#      postgres:
#        condition: service_healthy
#      redis:
#        condition: service_started
#      mongo:
#        condition: service_started
#      minio:
#        condition: service_started
#      rabbitmq:
#        condition: service_started
#
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    container_name: frontend
#    restart: unless-stopped
#    ports:
#      - "3000:80"
#    depends_on:
#      - api
#
#  nginx:
#    image: nginx:alpine
#    container_name: nginx
#    restart: unless-stopped
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - api
#      - frontend

  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:?set RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:?set RABBITMQ_DEFAULT_PASS}

  minio:
    image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z-cpuv1
    container_name: minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
#    volumes:
#      - ./storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?set MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?set MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?set POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:?set POSTGRES_DB}
    volumes:
      - ./database_schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} --dbname=$${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:?set REDIS_PASSWORD}
      REDIS_MASTER_PASSWORD: ${REDIS_PASSWORD:?set REDIS_PASSWORD}
    ports:
      - '6379:6379'

  mongo:
    image: 'mongo:latest'
    container_name: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:?set MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:?set MONGO_INITDB_ROOT_PASSWORD}

volumes:
  pgdata:
