// <auto-generated />
using System;
using ExamHub.Core.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExamHub.Core.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918152921_ModelCatchUp")]
    partial class ModelCatchUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.CognitiveLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("color_code");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<short>("LevelOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("level_order");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.HasKey("Id")
                        .HasName("pk_cognitive_levels");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_cognitive_levels_code");

                    b.HasIndex("LevelOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_cognitive_levels_level_order");

                    b.ToTable("cognitive_levels", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Cohort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<short>("EndYear")
                        .HasColumnType("smallint")
                        .HasColumnName("end_year");

                    b.Property<short>("GradeStart")
                        .HasColumnType("smallint")
                        .HasColumnName("grade_start");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<short>("NumClasses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("num_classes");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<short>("StartYear")
                        .HasColumnType("smallint")
                        .HasColumnName("start_year");

                    b.HasKey("Id")
                        .HasName("pk_cohorts");

                    b.HasIndex("SchoolId", "StartYear", "GradeStart")
                        .IsUnique()
                        .HasDatabaseName("ix_cohorts_school_id_start_year_grade_start");

                    b.ToTable("cohorts", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.CohortClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("class_name");

                    b.Property<int>("CohortId")
                        .HasColumnType("integer")
                        .HasColumnName("cohort_id");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_level_id");

                    b.Property<Guid?>("HomeroomTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("homeroom_teacher_id");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("school_year");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("section");

                    b.Property<short>("YearIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("year_index");

                    b.HasKey("Id")
                        .HasName("pk_cohort_classes");

                    b.HasIndex("GradeLevelId")
                        .HasDatabaseName("ix_cohort_classes_grade_level_id");

                    b.HasIndex("CohortId", "YearIndex", "Section")
                        .IsUnique()
                        .HasDatabaseName("ix_cohort_classes_cohort_id_year_index_section");

                    b.ToTable("cohort_classes", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.CohortClassTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("CohortClassId")
                        .HasColumnType("integer")
                        .HasColumnName("cohort_class_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("pk_cohort_class_teachers");

                    b.HasIndex("CohortClassId", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_cohort_class_teachers_cohort_class_id_subject_id");

                    b.ToTable("cohort_class_teachers", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.CohortMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CohortId")
                        .HasColumnType("integer")
                        .HasColumnName("cohort_id");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateOnly>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Section")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("section");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_cohort_members");

                    b.HasIndex("CohortId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_cohort_members_cohort_id_student_id");

                    b.ToTable("cohort_members", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.DifficultyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("ScoreWeight")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("score_weight");

                    b.Property<short>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_difficulty_levels");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_difficulty_levels_code");

                    b.ToTable("difficulty_levels", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("ClassName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("class_name");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(45)
                        .HasColumnName("duration_minutes");

                    b.Property<string>("ExamCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("exam_code");

                    b.Property<DateOnly?>("ExamDate")
                        .HasColumnType("date")
                        .HasColumnName("exam_date");

                    b.Property<Guid?>("ExamTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_template_id");

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_level_id");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<Guid?>("ParentExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_exam_id");

                    b.Property<string>("SchoolYear")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("school_year");

                    b.Property<short?>("Semester")
                        .HasColumnType("smallint")
                        .HasColumnName("semester");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<decimal>("TotalScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasDefaultValue(10.0m)
                        .HasColumnName("total_score");

                    b.Property<short?>("VariantIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("variant_index");

                    b.HasKey("Id")
                        .HasName("pk_exams");

                    b.HasIndex("ExamTemplateId")
                        .HasDatabaseName("ix_exams_exam_template_id");

                    b.HasIndex("GradeLevelId")
                        .HasDatabaseName("ix_exams_grade_level_id");

                    b.HasIndex("ParentExamId")
                        .HasDatabaseName("ix_exams_parent_exam_id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_exams_subject_id");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AnswersSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("answers_snapshot");

                    b.Property<string>("ContentSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_snapshot");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<decimal?>("Score")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("score");

                    b.Property<string>("SectionName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("section_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_exam_questions");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("ix_exam_questions_exam_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_exam_questions_question_id");

                    b.ToTable("exam_questions", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CloseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("close_at");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_level_id");

                    b.Property<short>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("max_attempts");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("OpenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_at");

                    b.Property<string>("PickMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Random")
                        .HasColumnName("pick_mode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_exam_sessions");

                    b.HasIndex("GradeLevelId")
                        .HasDatabaseName("ix_exam_sessions_grade_level_id");

                    b.HasIndex("SubjectId", "GradeLevelId", "Status")
                        .HasDatabaseName("ix_exam_sessions_subject_id_grade_level_id_status");

                    b.ToTable("exam_sessions", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamSessionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("CohortClassId")
                        .HasColumnType("integer")
                        .HasColumnName("cohort_class_id");

                    b.Property<int?>("CohortId")
                        .HasColumnType("integer")
                        .HasColumnName("cohort_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_exam_session_assignments");

                    b.HasIndex("CohortClassId")
                        .HasDatabaseName("ix_exam_session_assignments_cohort_class_id");

                    b.HasIndex("CohortId")
                        .HasDatabaseName("ix_exam_session_assignments_cohort_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_exam_session_assignments_session_id");

                    b.ToTable("exam_session_assignments", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamSessionExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_exam_session_exams");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("ix_exam_session_exams_exam_id");

                    b.HasIndex("SessionId", "ExamId")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_session_exams_session_id_exam_id");

                    b.ToTable("exam_session_exams", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("AttemptNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("attempt_no");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_passed");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("in_progress")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<decimal?>("TotalScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("total_score");

                    b.HasKey("Id")
                        .HasName("pk_exam_submissions");

                    b.HasIndex("ExamId", "StudentId")
                        .HasDatabaseName("ix_exam_submissions_exam_id_student_id");

                    b.ToTable("exam_submissions", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(45)
                        .HasColumnName("duration_minutes");

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_level_id");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<bool>("PreventDuplicate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("prevent_duplicate");

                    b.Property<bool>("ShuffleAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("shuffle_answers");

                    b.Property<bool>("ShuffleQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("shuffle_questions");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int?>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.Property<decimal>("TotalScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasDefaultValue(10.0m)
                        .HasColumnName("total_score");

                    b.HasKey("Id")
                        .HasName("pk_exam_templates");

                    b.HasIndex("GradeLevelId")
                        .HasDatabaseName("ix_exam_templates_grade_level_id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_exam_templates_subject_id");

                    b.ToTable("exam_templates", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamTemplateSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("CognitiveLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("cognitive_level_id");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ExamTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_template_id");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<short>("PctEasy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("pct_easy");

                    b.Property<short>("PctHard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("pct_hard");

                    b.Property<short>("PctMedium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("pct_medium");

                    b.Property<short>("PctVeryHard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("pct_very_hard");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("question_count");

                    b.Property<int?>("QuestionTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("question_type_id");

                    b.Property<decimal?>("ScorePerQuestion")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("score_per_question");

                    b.Property<string>("SectionName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("section_name");

                    b.Property<short>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("sort_order");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_exam_template_sections");

                    b.HasIndex("CognitiveLevelId")
                        .HasDatabaseName("ix_exam_template_sections_cognitive_level_id");

                    b.HasIndex("ExamTemplateId")
                        .HasDatabaseName("ix_exam_template_sections_exam_template_id");

                    b.HasIndex("QuestionTypeId")
                        .HasDatabaseName("ix_exam_template_sections_question_type_id");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_exam_template_sections_topic_id");

                    b.ToTable("exam_template_sections", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.GradeLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<short>("GradeNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("grade_number");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_grade_levels");

                    b.HasIndex("GradeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_grade_levels_grade_number");

                    b.ToTable("grade_levels", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("audio_url");

                    b.Property<int?>("CognitiveLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("cognitive_level_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentPlain")
                        .HasColumnType("text")
                        .HasColumnName("content_plain");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("DifficultyLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty_level_id");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("question_type_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Source")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("CognitiveLevelId")
                        .HasDatabaseName("ix_questions_cognitive_level_id");

                    b.HasIndex("DifficultyLevelId")
                        .HasDatabaseName("ix_questions_difficulty_level_id");

                    b.HasIndex("QuestionTypeId")
                        .HasDatabaseName("ix_questions_question_type_id");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_questions_topic_id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.QuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentPlain")
                        .HasColumnType("text")
                        .HasColumnName("content_plain");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<short>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_question_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_question_answers_question_id");

                    b.ToTable("question_answers", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.QuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_question_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_question_types_code");

                    b.ToTable("question_types", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_schools");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_schools_code");

                    b.ToTable("schools", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.SchoolMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_school_members");

                    b.HasIndex("SchoolId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_school_members_school_id_user_id");

                    b.ToTable("school_members", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_level_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_subjects");

                    b.HasIndex("GradeLevelId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_subjects_grade_level_id_code");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.SubmissionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EssayContent")
                        .HasColumnType("text")
                        .HasColumnName("essay_content");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_question_id");

                    b.Property<string>("Feedback")
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<Guid?>("GradedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("graded_by");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<decimal>("ScoreEarned")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("score_earned");

                    b.PrimitiveCollection<Guid[]>("SelectedAnswerIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("selected_answer_ids");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("Id")
                        .HasName("pk_submission_answers");

                    b.HasIndex("ExamQuestionId")
                        .HasDatabaseName("ix_submission_answers_exam_question_id");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_submission_answers_submission_id");

                    b.ToTable("submission_answers", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.TeacherSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_teacher_subjects");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_teacher_subjects_subject_id");

                    b.HasIndex("UserId", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_teacher_subjects_user_id_subject_id");

                    b.ToTable("teacher_subjects", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("pk_topics");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_topics_parent_id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_topics_subject_id");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Cohort", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.School", "School")
                        .WithMany("Cohorts")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cohorts_schools_school_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.CohortClass", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.Cohort", "Cohort")
                        .WithMany("Classes")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cohort_classes_cohorts_cohort_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.GradeLevel", "GradeLevel")
                        .WithMany()
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cohort_classes_grade_levels_grade_level_id");

                    b.Navigation("Cohort");

                    b.Navigation("GradeLevel");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.CohortMember", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.Cohort", "Cohort")
                        .WithMany("Members")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cohort_members_cohorts_cohort_id");

                    b.Navigation("Cohort");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Exam", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.ExamTemplate", "ExamTemplate")
                        .WithMany()
                        .HasForeignKey("ExamTemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_exams_exam_templates_exam_template_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.GradeLevel", "GradeLevel")
                        .WithMany()
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exams_grade_levels_grade_level_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.Exam", "ParentExam")
                        .WithMany("Variants")
                        .HasForeignKey("ParentExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_exams_exams_parent_exam_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exams_subjects_subject_id");

                    b.Navigation("ExamTemplate");

                    b.Navigation("GradeLevel");

                    b.Navigation("ParentExam");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamQuestion", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_questions_exams_exam_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_questions_questions_question_id");

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamSession", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.GradeLevel", "GradeLevel")
                        .WithMany()
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_sessions_grade_levels_grade_level_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_sessions_subjects_subject_id");

                    b.Navigation("GradeLevel");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamSessionAssignment", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.CohortClass", "CohortClass")
                        .WithMany()
                        .HasForeignKey("CohortClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_exam_session_assignments_cohort_classes_cohort_class_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.Cohort", "Cohort")
                        .WithMany()
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_exam_session_assignments_cohorts_cohort_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.ExamSession", null)
                        .WithMany("Assignments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_session_assignments_exam_sessions_session_id");

                    b.Navigation("Cohort");

                    b.Navigation("CohortClass");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamSessionExam", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_session_exams_exams_exam_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.ExamSession", null)
                        .WithMany("Exams")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_session_exams_exam_sessions_session_id");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamSubmission", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_submissions_exams_exam_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.ExamSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_exam_submissions_public_exam_sessions_session_id");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamTemplate", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.GradeLevel", "GradeLevel")
                        .WithMany()
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_templates_grade_levels_grade_level_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_templates_subjects_subject_id");

                    b.Navigation("GradeLevel");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamTemplateSection", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.CognitiveLevel", "CognitiveLevel")
                        .WithMany()
                        .HasForeignKey("CognitiveLevelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_exam_template_sections_cognitive_levels_cognitive_level_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.ExamTemplate", "ExamTemplate")
                        .WithMany("Sections")
                        .HasForeignKey("ExamTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_template_sections_exam_templates_exam_template_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.QuestionType", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_exam_template_sections_question_types_question_type_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_exam_template_sections_topics_topic_id");

                    b.Navigation("CognitiveLevel");

                    b.Navigation("ExamTemplate");

                    b.Navigation("QuestionType");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Question", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.CognitiveLevel", "CognitiveLevel")
                        .WithMany()
                        .HasForeignKey("CognitiveLevelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_questions_cognitive_levels_cognitive_level_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.DifficultyLevel", "DifficultyLevel")
                        .WithMany()
                        .HasForeignKey("DifficultyLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questions_difficulty_levels_difficulty_level_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.QuestionType", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questions_question_types_question_type_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questions_topics_topic_id");

                    b.Navigation("CognitiveLevel");

                    b.Navigation("DifficultyLevel");

                    b.Navigation("QuestionType");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.QuestionAnswer", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_answers_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.SchoolMember", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.School", "School")
                        .WithMany("Members")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_school_members_schools_school_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Subject", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.GradeLevel", "GradeLevel")
                        .WithMany("Subjects")
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subjects_grade_levels_grade_level_id");

                    b.Navigation("GradeLevel");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.SubmissionAnswer", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.ExamQuestion", "ExamQuestion")
                        .WithMany()
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_answers_exam_questions_exam_question_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.ExamSubmission", "Submission")
                        .WithMany("Answers")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submission_answers_exam_submissions_submission_id");

                    b.Navigation("ExamQuestion");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.TeacherSubject", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_subjects_subjects_subject_id");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Topic", b =>
                {
                    b.HasOne("ExamHub.Core.Domain.Entities.Topic", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_topics_topics_parent_id");

                    b.HasOne("ExamHub.Core.Domain.Entities.Subject", "Subject")
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topics_subjects_subject_id");

                    b.Navigation("Parent");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Cohort", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Exam", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamSession", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamSubmission", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.ExamTemplate", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.GradeLevel", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.School", b =>
                {
                    b.Navigation("Cohorts");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("ExamHub.Core.Domain.Entities.Topic", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
