#!/bin/bash
set -e
SERVICE="postgres"
DB="examhub"
DBUSER="postgres"
echo "Dang chay 00_reset.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "00_reset.sql"
echo "Dang chay 00_topics.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "00_topics.sql"
echo "Dang chay g01_MATH.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "g01_MATH.sql"
echo "Dang chay g01_VIE.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "g01_VIE.sql"
echo "Dang chay g02_MATH.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "g02_MATH.sql"
echo "Dang chay g02_VIE.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "g02_VIE.sql"
echo "Dang chay g03_MATH.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "g03_MATH.sql"
echo "Dang chay g03_TNXH.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "g03_TNXH.sql"
echo "Dang chay g03_VIE.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "g03_VIE.sql"
echo "Dang chay g04_MATH.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "g04_MATH.sql"
echo "Dang chay g04_SCI.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "g04_SCI.sql"
echo "Dang chay g04_VIE.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "g04_VIE.sql"
echo "Dang chay g05_MATH.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "g05_MATH.sql"
echo "Dang chay g05_SCI.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "g05_SCI.sql"
echo "Dang chay g05_VIE.sql ..."
docker compose exec -T "$SERVICE" psql -U "$DBUSER" -d "$DB" -v ON_ERROR_STOP=1 < "g05_VIE.sql"
echo "Hoan tat!"